/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme\ink-violet-theme.ts
 * Command: astryx theme build theme\ink-violet-theme.ts --out theme\ink-violet.css
 * Generated: 2026-07-09T10:41:26.149Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const inkVioletTheme: DefinedTheme;
